config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "users#index"

  resources :users, only: [:show] do
    resources :posts, only: [:new, :create, :show, :index, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end
      can :destroy, Comment do |comment|
        comment.author == user
      end
      can :create, Post
      can :create, Comment
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, class_name: :Post, foreign_key: :post_id
  belongs_to :author, class_name: :User, foreign_key: :author_id

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, class_name: :Post, foreign_key: :post_id
  belongs_to :author, class_name: :User, foreign_key: :author_id

  after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id

  validates :title, presence: true, length: { maximum: 200 }
  validates :body, presence: true, length: { minimum: 5 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  before_action :set_post, only: [:show]
  def index
    posts = Post.all.order(:id)
    render json: posts, status: :ok
  end

  def show
    render json: @post, status: :ok
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::ApplicationController
  before_action :set_author, only: [:show]
  def index
    authors = User.all.order(:id)
    render json: authors, status: :ok
  end

  def show
    render json: @author, status: :ok
  end

  private

  def set_author
    @author = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comments = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}"
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    author = @comment.post.author
    post = @comment.destroy
    if @comment.destroy
      flash[:notice] = 'Comment deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to user_post_url(author, post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(author_id: current_user.id, post_id: @post.id)
    @like.post_id = params[:post_id]
    @like.author_id = current_user.id
    if @like.save
      redirect_to "/users/#{@post.author.id}/posts/#{@post.id}"
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:author)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to "/users/#{current_user.id}/posts"
    else
      render :new
    end
  end

  def destroy
    user = current_user
    @post = Post.find_by(id: params[:id], author_id: params[:user_id])
    @post.likes.destroy_all
    @post.comments.destroy_all

    if @post.destroy
      flash[:notice] = 'Post deleted!'
    else
      flash[:alert] = 'Error! Please try again later.'
    end
    redirect_to user_posts_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div mt-5 d-flex align-items-center flex-column>
<h4>Add comment</h4>
<%= form_with model: @comments, url: user_post_comments_path do |f| %>
    <%= f.text_area :text, placeholder: 'Add Your Comment', class:'form-control'%><br>
    <%= f.submit "Post Comment", class:'btn btn-primary' %><br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/posts/index.html.erb
<div class="user-posts-page">
 <%= render "shared/user_dets", user: @user %>
  <div class="post-comm">
   <div class="cont">
      <%= link_to "Add New Post", new_user_post_path(user_id: @user.id), class:"btn btn-primary" %> 
      <h3 class="all">All Posts</h3>
    <div>
   <% @posts.each_with_index do |post| %>
     <%= link_to user_post_path(user_id:@user.id, id: post.id), class:'nav-link' do %>
       <%= render "shared/post_dets", post: post %>
        <div class="comment-section">
          <% if post.most_recent_comments.empty? %>
            <p class="comment-body">No comments</p>
          <% else %>
            <% post.most_recent_comments.each do |comment| %>
             <p class="comment-body"><%= comment.author.name %>: <%= comment.text %></p>
            <%end%>
          <%end%>
        </div>
      <% end %>
   <%end%>
  </div>
   <button class="pagi-btn">pagination</button>
</div>

app/views/posts/new.html.erb
<div class="new-post">
    <h1>Add New Post</h1>
    <%= form_with model: @post, url: user_posts_path do |f| %>
        <div class="mb-3">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'Enter title', class: "form-control" %>
        </div>
        <div class="mb-3">
        <%= f.label :body %>
        <%= f.text_area :body, placeholder: 'Write post... ', class: "form-control" %>
        <div>
        <%= f.submit 'Create post', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="single-post">
 <% if can? :destroy, @post %>
   <%= button_to "Delete Post", user_post_path(id: @post.id), method: :delete, class:"delete-post" %>
  <% end %>
  <div class="post-body">
    <div class="post-intro">
      <strong class="post-title">Post by: <%= @post.author.name %></strong>
      <p>
        Comments: <%= @post.comments_counter %> 
        Likes: <%= @post.likes_counter %>
      </p>
    </div>
    <h3 class="p-title"><%= @post.title %></h3>
    <p class="post-text"><%= @post.body %></p>
  </div>
    <div class="comment-section">
    <div class="engage">
    <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |f| %>
       <%= f.submit "Like", class: "btn btn-primary" %>
    <% end %> 
    <%= link_to "Add Comment", new_user_post_comment_path(user_id: @user.id, post_id: @post.id), class: "btn btn-primary" %>
    </div>
    <% if @post.comments.empty? %>
    <p class="comment-body">No comments yet</p>
  <% else %>
      <% @post.comments.each do |comment| %>
        <p class="comment-body"><%= comment.author.name %>: <%= comment.text %></p>
           <% if can? :destroy, comment %>
           <%= button_to "Delete", user_post_comment_path(user_id: @user.id, post_id: @post.id, id: comment.id), method: :delete, class:"delete-comment" %>
         <% end %>
      <%end%>
      <%end%>
  </div>
</div>

app/views/shared/_post_dets.html.erb
<div class="post-partial">
  <h3 class="post-title"><%= post.title %></h3>
    <p class="post"><%= post.body %></p>
    <div class="engagement">
     <p>
      Comments: <%= post.comments_counter %>
      Likes: <%= post.likes_counter %>
     </p>
    </div>
</div>

app/views/shared/_user_dets.html.erb
<div class="user-info-container">
   <div class="user-photo">
    <img class="user-img" src=<%= user.photo %> alt="profile photo" />
   </div>
   <div class="user-dets">
     <h3 class="name"><%= user.name %></h3>
     <span class="post-count">Number of posts: <%= user.posts.count %></span>
   </div>
</div>

app/views/users/index.html.erb
<div class="all-users">
<% @users.each do |user| %>
    <%= link_to(user) do %>
      <%= render "shared/user_dets", user: user %>
    <%end%>
  <%end%>
</div>

app/views/users/show.html.erb
<div class="user-page">
  <%= render "shared/user_dets", user: @user %>
    <div class="user-bio">
     <strong class="bio">Bio: </strong> <br>
     <p><%= @user.bio %></p>
    </div>
    <div class="user-posts">
    <% @user.most_recent_posts.each do |post| %>
        <%= link_to user_post_path(user_id:@user.id, id: post.id), class:'nav-link' do%>
      <%= render "shared/post_dets", post: post %>
        <%end%>
    <%end%>
    </div>
    <%= link_to 'See all posts', user_posts_path(@user), class: "btn-btn primary post-btn"%>
</div>